/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.artistas;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego
 */
public class VentanaOpciones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaOpciones
     */
    public VentanaOpciones() {
        initComponents();
        
        
        
        cmbArtistas.addItem("Maria Becerra");
        cmbArtistas.addItem("DUKI");
        cmbArtistas.addItem("Nicki Nicole");
        cmbArtistas.addItem("Bad Bunny");
        cmbArtistas.addItem("Feid");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblElijaArtista = new javax.swing.JLabel();
        cmbArtistas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblimagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("ARTISTAS ARGENTINOS");

        lblElijaArtista.setText("Elija su artista preferido:");

        cmbArtistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArtistasActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElijaArtista)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cmbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addComponent(lblElijaArtista)
                .addGap(18, 18, 18)
                .addComponent(cmbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArtistasActionPerformed
        // TODO add your handling code here:
        
        Artista MariaBecerra = new Artista("Cantante Argentina", "src/com.mycompany/mariaaudio.wav", "/com/mycompany/artistas/imagenes/mariaBecerra.jpg");
        Artista DUKI = new Artista("Cantante Argentino", "src/com.mycompany/dukiaudio.wav", "/com/mycompany/artistas/imagenes/duki.jpg");
        Artista NickiNicole = new Artista("Buena Cantante Argentina", "src/com.mycompany/nickiaudio.wav", "/com/mycompany/artistas/imagenes/nickiNicole.jpg");
        Artista BadBunny = new Artista("Cantante raro", "src/com.mycompany/badbunnyaudio.wav", "/com/mycompany/artistas/imagenes/BadBunny.jpg");
        Artista Feid = new Artista("Cantante Colombiano", "src/com.mycompany/feidaudio.wav", "/com/mycompany/artistas/imagenes/feid.jpg");
        
        if(cmbArtistas.getSelectedItem().toString() == "Maria Becerra"){
           
            
            txtDescripcion.setText(MariaBecerra.getDescripcion());
            //lblimagen.setIcon(new ImageIcon(MariaBecerra.getImagen()));
            lblimagen.setIcon(new ImageIcon("src/main/java/com/mycompany/artistas/imagenes/mariaBecerra.jpg"));
            //jPanel1.add(lblimagen);
            
            
        }
        else if(cmbArtistas.getSelectedItem().toString() == "DUKI"){
            
            //ImageIcon icon = new ImageIcon(DUKI.getImagen());
            
            txtDescripcion.setText(DUKI.getDescripcion());
            lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(DUKI.getImagen())));
            
            //lblimagen.setIcon(icon);
        }
        else if(cmbArtistas.getSelectedItem().toString() == "Nicki Nicole"){
            
            //ImageIcon icon = new ImageIcon(NickiNicole.getImagen());
            
            txtDescripcion.setText(NickiNicole.getDescripcion());
            lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(NickiNicole.getImagen())));
            
            //lblimagen.setIcon(icon);
        }
        else if(cmbArtistas.getSelectedItem().toString() == "Bad Bunny"){
            
            //ImageIcon icon = new ImageIcon(BadBunny.getImagen());
            
            txtDescripcion.setText(BadBunny.getDescripcion());
            lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(BadBunny.getImagen())));
            //lblimagen.setIcon(icon);
        }
        else if(cmbArtistas.getSelectedItem().toString() == "Feid"){
            
            //ImageIcon icon = new ImageIcon(Feid.getImagen());
            
            txtDescripcion.setText(Feid.getDescripcion());
            lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource(Feid.getImagen())));
            //lblimagen.setIcon(icon);
        }
    }//GEN-LAST:event_cmbArtistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbArtistas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElijaArtista;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
