/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pruebagraficos;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Diego
 */
public class Animacion extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form Animacion
     */
    
    int x = getWidth()/2;
    Thread hilo;
    
    
    public Animacion() {
        initComponents();
        
        hilo = new Thread(this);
    }
    
    public void paint(Graphics g){
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.red); 
        g.fillOval(x, getHeight()/2, 30, 30);
    }
    
    public void inicio(){
        try {
            hilo.start();
        } catch (Exception e) {
            System.out.println("ERROR:  " + e.getMessage());
        }
    }
    
    public void pausa(){
        hilo.suspend();
    }
    
    public void continuar(){
        hilo.resume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        try {
            while(true){
                while(x < getWidth()-30){
                    Thread.sleep(1);
                    x += 10;
                    repaint();
                }
                while(x > 8){
                    Thread.sleep(1);
                    x -= 10; 
                    repaint();
                }
            }
        } catch (Exception e) {
            System.out.println("ERRORRRRRR: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
